### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by jorgenb** [Jorijn/laravel-security-checker#11]
Would be nice to have it updated to support 5.5+.

**Comment by Jorijn** [comment]
Hi! Well, no. I've been busy, that's all.

There is an [open pull request](https://github.com/Jorijn/laravel-security-checker/pull/10) to support Laravel 5.5 which I haven't been getting to to fix before merging in. Feel free to complete the PR and I'll be happy to create a new tag.

**Comment by jorgenb** [comment]
Thanks for responding.

I think it is just a question of upgrading phpunit to ~6.0 and your tests will pass. Upgrading to ~6.0 should be backward compatible with Laravel 5.4.x.
