### ISSUE TITLE
Mail function not working

### ISSUE THREAD

**Issue by patrick-hintermayer** [Jorijn/laravel-security-checker#14]
I use the latest Larvel 5.5 version, installed laravel-security-checker (0.30.0) as described, set both .env constants, but also tried setting values directly in the copied config file and ran `php artisan security-check:email`. After a few seconds, I got the message

> Expected response code 250 but got code "354", with message "354 Enter mail, end with "." on a line by itself

`php artisan security-check:now` ist working properly.

**Comment by Jorijn** [comment]
Hi Patrick,

I tried and tested it again for you on 5.5 and 5.6. On my end it works. What is your configuration? Don't forget to mask your email password.

**Comment by Jorijn** [comment]
Closed due to inactivity.
