### ISSUE TITLE
Add Laravel 5.8 support

### ISSUE THREAD

**Issue by matijakovacevic** [Jorijn/laravel-security-checker#18]
5.8 support?

**Comment by Jorijn** [comment]
As of now it's not officially released yet. When it is, I'll review the upgrade path and include support.

If you want, feel free to take this on and submit a PR. :-)

**Comment by matijakovacevic** [comment]
It was realeased this Tuesday
https://laravel.com/docs/5.8

**Comment by DevDavido** [comment]
I opened a PR #19, feel free to contribute @matijakovacevic

**Comment by matijakovacevic** [comment]
Sry, didn't have time to contribute but I saw you did it entirely on your own @DevDavido. 
Kudoz! And thanks!

**Comment by Jorijn** [comment]
I just pushed v1.1.0 out which includes support for Laravel 5.8. Thanks for your help @DevDavido :-)
