### ISSUE TITLE
Return non-zero exit code in command

### ISSUE THREAD

**Issue by michiruf** [Jorijn/laravel-security-checker#24]
The command(s) should return a non-zero exit code to indicate if there are vulnerabilities or not.

Given one wants to use this library in an CI environment, there must be non-zero return values to stop the build process from processing.

**Comment by Jorijn** [comment]
Hey @michiruf. 

Thanks for reporting this. I have corrected the command and it now returns `0` when no vulnerabilities were found and `1` when there are. It's tagged as `v1.2.0`.
