### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by hilal-hipster** [Jorijn/laravel-security-checker#30]
**Laravel Version** -- 6.18.11
**Steps to reproduce**
Run **composer require jorijn/laravel-security-checker** on Laravel project having version as 6.18.1 it fails and the output is :

Using version ^2.1 for jorijn/laravel-security-checker
./composer.json has been updated
Loading composer repositories with package information
Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2.0 is now available and you should upgrade. See https://getcomposer.org/2
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for jorijn/laravel-security-checker ^2.1 -> satisfiable by jorijn/laravel-security-checker[v2.1.0].
    - Conclusion: remove guzzlehttp/guzzle 6.5.3
    - Conclusion: don't install guzzlehttp/guzzle 6.5.3
    - jorijn/laravel-security-checker v2.1.0 requires guzzlehttp/guzzle ^7.0 -> satisfiable by guzzlehttp/guzzle[7.0.0, 7.0.0-beta.1, 7.0.0-beta.2, 7.0.0-rc.1, 7.0.1, 7.0.x-dev, 7.1.0, 7.1.1, 7.2.0, 7.1.x-dev].
    - Can only install one of: guzzlehttp/guzzle[7.0.0, 6.5.3].
    - Can only install one of: guzzlehttp/guzzle[7.0.0-beta.1, 6.5.3].
    - Can only install one of: guzzlehttp/guzzle[7.0.0-beta.2, 6.5.3].
    - Can only install one of: guzzlehttp/guzzle[7.0.0-rc.1, 6.5.3].
    - Can only install one of: guzzlehttp/guzzle[7.0.1, 6.5.3].
    - Can only install one of: guzzlehttp/guzzle[7.0.x-dev, 6.5.3].
    - Can only install one of: guzzlehttp/guzzle[7.1.0, 6.5.3].
    - Can only install one of: guzzlehttp/guzzle[7.1.1, 6.5.3].
    - Can only install one of: guzzlehttp/guzzle[7.2.0, 6.5.3].
    - Can only install one of: guzzlehttp/guzzle[7.1.x-dev, 6.5.3].
    - Installation request for guzzlehttp/guzzle (locked at 6.5.3) -> satisfiable by guzzlehttp/guzzle[6.5.3].

Installation failed, reverting ./composer.json to its original content.
![Screenshot from 2020-11-05 12-45-55](https://user-images.githubusercontent.com/43673169/98209697-63b69480-1f65-11eb-9029-83dd46a9e13a.png)

**Comment by hilal-hipster** [comment]
@Jorijn Could you please help me out

**Comment by Jorijn** [comment]
Hey. Since Laravel switched to SEMVER, I updated the major version to v2. You are on 6.18, which is pre-semver era for Laravel. You should be able to use the v1.2 version of this package like this:

`$ composer require jorijn/laravel-security-checker:^1.2` 

I do however recommend that you upgrade your Laravel installation.

**Comment by hilal-hipster** [comment]
> Hey. Since Laravel switched to SEMVER, I updated the major version to v2. You are on 6.18, which is pre-server era for Laravel. You should be able to use the v1.2 version of this package like this:
> 
> `$ composer require jorijn/laravel-security-checker:^1.2`
> 
> I do however recommend that you upgrade your Laravel installation.
Thanks, it works now. (y)
About upgrading the Laravel: Noted will update version soon or else in version 2 of the project.
