### ISSUE TITLE
sensiolabs/security-checker is abandoned

### ISSUE THREAD

**Issue by the-hardik-sisodia** [Jorijn/laravel-security-checker#32]
The dependency `sensiolabs/security-checker` has been abandoned recently, which will stop working at the end of January 2021. [**`Open-Source CLI tool`**](https://github.com/fabpot/local-php-security-checker) or [**`Symphony CLI`**](https://symfony.com/download) has been suggested

**Comment by Jorijn** [comment]
Thanks! I'll see if I can push out a fix before the end of January.

**Comment by paras-malhotra** [comment]
I sent a PR to fix this.
