### ISSUE TITLE
Is this package abandoned?

### ISSUE THREAD

**Issue by jezmck** [Jorijn/laravel-security-checker#37]
I get the following in `composer` output, suggesting that it is. If so, this repo needs to be archived or similar.

```Package sensiolabs/security-checker is abandoned, you should avoid using it. Use https://github.com/fabpot/local-php-security-checker instead.```

**Comment by Jorijn** [comment]
Hey,

It's not. There is a new version which replaced the sensiolabs package. Check your constraints and update.

Do let me know if you work it out :)
