### ISSUE TITLE
Is the package abandoned? When is Laravel 9 support coming?

### ISSUE THREAD

**Issue by davidabadi** [Jorijn/laravel-security-checker#41]
There has not been any changes to the package in almost a year and no support for Laravel 9. Would like to know if it is abandoned?

**Comment by Jorijn** [comment]
No, this package hasn't been abandoned. Frankly, I don't have a lot of time but from a feature perspective; The package is complete. It does what it is supposed to do and adding features for the sake of features isn't how I'd like to support things.

But, you're right: Laravel 9 support is highly overdue. I've been working on it this weekend and it is looking good. I just need to check and test some stuff before shipping. 

Be sure to watch this repository. I'll finish it soon :)

**Comment by davidabadi** [comment]
Great news. Thanks for the work you do for the community!
